//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessorSubjects
    {
        public int ID { get; set; }
        public Nullable<int> professorID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Professors Professors { get; set; }
        public virtual Professors Professors1 { get; set; }
        public virtual Subjects Subjects { get; set; }
        public virtual Subjects Subjects1 { get; set; }
        public virtual Subjects Subjects2 { get; set; }
    }
}
