//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProfessorSubject
    {
        public int ID { get; set; }
        public Nullable<int> professorID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Professor Professor { get; set; }
        public virtual Professor Professor1 { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Subject Subject1 { get; set; }
        public virtual Subject Subject2 { get; set; }
    }
}
