//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentsSubjects = new HashSet<StudentsSubject>();
        }
    
        public int ID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<decimal> NationalID { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string SurName { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string Image { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Dept Dept { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Level Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsSubject> StudentsSubjects { get; set; }
    }
}
