//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subjects()
        {
            this.ProfessorSubjects = new HashSet<ProfessorSubjects>();
            this.ProfessorSubjects1 = new HashSet<ProfessorSubjects>();
            this.ProfessorSubjects2 = new HashSet<ProfessorSubjects>();
            this.StudentsSubjects = new HashSet<StudentsSubjects>();
            this.Subjects11 = new HashSet<Subjects>();
        }
    
        public int ID { get; set; }
        public string Subjects1 { get; set; }
        public Nullable<double> CreditHours { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> PreSubjectID { get; set; }
        public string Day { get; set; }
        public Nullable<double> TimeFrome { get; set; }
        public Nullable<double> TimeTo { get; set; }
    
        public virtual Dept Dept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfessorSubjects> ProfessorSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfessorSubjects> ProfessorSubjects1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfessorSubjects> ProfessorSubjects2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsSubjects> StudentsSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subjects> Subjects11 { get; set; }
        public virtual Subjects Subjects2 { get; set; }
    }
}
