//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.ProfessorSubjects = new HashSet<ProfessorSubject>();
            this.ProfessorSubjects1 = new HashSet<ProfessorSubject>();
            this.ProfessorSubjects2 = new HashSet<ProfessorSubject>();
            this.StudentsSubjects = new HashSet<StudentsSubject>();
            this.Subjects1 = new HashSet<Subject>();
        }
    
        public int ID { get; set; }
        public string Subjects { get; set; }
        public Nullable<double> CreditHours { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> PreSubjectID { get; set; }
        public string Day { get; set; }
        public Nullable<double> TimeFrome { get; set; }
        public Nullable<double> TimeTo { get; set; }
    
        public virtual Dept Dept { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfessorSubject> ProfessorSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfessorSubject> ProfessorSubjects1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProfessorSubject> ProfessorSubjects2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentsSubject> StudentsSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subject> Subjects1 { get; set; }
        public virtual Subject Subject1 { get; set; }
    }
}
